changelog:
  exclude:
    authors:
      - github-actions[bot]
    labels:
      - ignore-for-release
  categories:
    - title: evo-data-converters-common
      labels:
        - common
    - title: evo-data-converters-gef
      labels:
        - gef
    - title: evo-data-converters-gocad
      labels:
        - gocad
    - title: evo-data-converters-omf
      labels:
        - omf
    - title: evo-data-converters-resqml
      labels:
        - resqml
    - title: evo-data-converters-ubc
      labels:
        - ubc
    - title: evo-data-converters-vtk
      labels:
        - vtk
    - title: Breaking Changes 🛠
      labels:
        - semver-major
        - breaking-change
    - title: Other Changes
      labels:
        - "*"
    - title: evo-data-converters-duf import
      labels:
        - duf
