#  Copyright © 2025 Bentley Systems, Incorporated
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

import typing
from pathlib import Path

import pint
from evo_schemas.elements import Unit_V1_0_1 as Unit
from pint_pandas import PintType

import evo.logging

logger = evo.logging.getLogger("data_converters")


class UnitMapper:
    """Map units between Pint and EVO"""

    @staticmethod
    def lookup(pt: PintType) -> Unit | None:
        """Map a PintType to its corresponding Evo Unit"""
        key = str(pt.units)
        return _pint_lookup.get(key, None)


# table mapping Evo Unit_V1_0_1 values to the
# corresponding Pint Unit string value:
#
# NOTE: This table is incomplete, any entry with a value of None needs to have a pint value
#       assigned.  New pint types can be defines in evo_units.txt if required
#
#       See: https://github.com/geosoft-as/osdu-uom
#            https://github.com/hgrecco/pint/blob/master/pint/default_en.txt
#
#
_translation_table: dict[str, str | None] = {
    "dAPI": None,
    "gAPI": None,
    "nAPI": None,
    "O": None,
    "dB/O": None,
    "B/O": None,
    "TD[API]/(Pa.s)": None,
    "TD[API].m": None,
    "cmH2O[4degC]": None,
    "inH2O[32degF]": None,
    "inH2O[39degF]": None,
    "mmHg[0degC]": None,
    "umHg[0degC]": None,
    "TD[API]": None,
    "D[API]": None,
    "ft[BnA]": None,
    "ft[BnB]": None,
    "ft[Br36]": None,
    "ft[Br65]": None,
    "ft[Cla]": None,
    "ft[GC]": None,
    "ft[Ind]": None,
    "ft[Ind37]": None,
    "ft[Ind62]": None,
    "ft[Ind75]": None,
    "ft[Se]": None,
    "ft[SeT]": None,
    "link[BnA]": None,
    "link[BnB]": None,
    "link[Cla]": None,
    "link[Se]": None,
    "link[SeT]": None,
    "m[Ger]": None,
    "mi[naut]": None,
    "mi[nautUK]": None,
    "yd[BnA]": None,
    "yd[BnB]": None,
    "yd[Cla]": None,
    "yd[Ind]": None,
    "yd[Ind37]": None,
    "yd[Ind62]": None,
    "yd[Ind75]": None,
    "yd[Se]": None,
    "yd[SeT]": None,
    "chain[BnA]": None,
    "chain[BnB]": None,
    "chain[Cla]": None,
    "chain[Ind37]": None,
    "chain[Se]": None,
    "chain[SeT]": None,
    #
    # All the values below this point are complete,
    # and all the values above are incomplete.
    #
    "gn": "gravity",
    "mgn": "mgravity",
    "$": "dollar",
    "$/t": "dollar/tonne",
    "$/ton[US]": "dollar/short_ton",
    "1/2 ms": "half_millisecond",
    "1/30 m/m": "m/thirty_m",
    "1/30 lbf/m": "lbf/thirty_m",
    "1/30 N/m": "N/thirty_m",
    "1/30 cm3/min": "cm^3/thirty_min",
    "1/30 dega/ft": "deg/thirty_ft",
    "1/30 dega/m": "deg/thirty_m",
    "1/16 in": "sixteenth_of_inch",
    "1/32 in": "thirtysecond_of_inch",
    "1/64 in": "sixtyfourth_of_inch",
    "1/2 ft": "half_foot",
    "0.1 ft[US]": "decius_survey_ft",
    "0.1 in": "din",
    "0.1 yd": "dyd",
    "0.1 ft": "dft",
    "0.1 lbm/bbl": "lb/dabbl",
    "0.1 gal[US]/bbl": "gallon/dabbl",
    "0.1 L/bbl": "L/dabbl",
    "0.1 pt[US]/bbl": "pint/dabbl",
    "0.01 L/km": "L/deca_km",
    "0.01 bbl/bbl": "bbl/hectobbl",
    "0.01 lbf/ft": "lbf/hectoft",
    "0.01 lbf/ft2": "lbf/hectosquare_foot",
    "0.01 dega/ft": "deg/hectofoot",
    "0.01 ct/t": "ct/hectotonne",  # carats per 100 ton
    "0.01 deltaF/ft": "F/hectoft",  # delta Fahrenheit per hundred foot
    "0.01 ft/ft": "ft/hectoft",
    "0.01 grain/ft3": "grain/hectocubic_feet",
    "0.01 psi/ft": "psi/hectoft",
    "0.01 lbm/ft2": "lb/hectosquare_foot",
    "0.01 L/kg": "L/hecto_kg",
    "0.01 dm3/km": "dm^3/hecto_km",
    "0.001 kPa2/cP": "kPa^2/kP",  # kilopascal squared per thousand centipoise
    "0.001 d/ft3": "d/kcubic_feet",
    "0.001 h/ft": "h/kft",
    "0.001 d/ft": "d/kft",
    "0.001 lbm/gal[US]": "lb/kgallon",
    "0.001 lbm/gal[UK]": "lb/kUK_gallon",
    "0.001 lbm/bbl": "lb/kbbl",
    "0.001 psi/ft": "psi/kft",
    "0.001 bbl/ft3": "bbl/kcubic_foot",
    "0.001 bbl/m3": "bbl/kcubic_metre",
    "0.001 gal[UK]/bbl": "UK_gallon/kbbl",
    "0.001 gal[UK]/gal[UK]": "UK_gallon/kUK_gallon",
    "0.001 gal[US]/bbl": "gallon/kbbl",
    "0.001 gal[US]/ft3": "gallon/kcubic_foot",
    "0.001 gal[US]/gal[US]": "gallon/kgallon",
    "0.001 pt[US]/bbl": "pint/kbbl",
    "0.001 pt[UK]/bbl": "UK_pint/kbbl",
    ".001 pt[US]/bbl": "pint/kbbl",
    ".001 pt[UK]/bbl": "UK_pint/kbbl",
    "0.001 seca": "karc_second",
    "1E-6 m3/(m3.deltaC)": "cubic_metre/(Mcubic_metre.C)",  # (cubic metre per million cubic metre) per delta C
    "1E-6 m3/(m3.deltaF)": "cubic_metre/(Mcubic_metre.F)",  # (cubic metre per million cubic metre) per delta Fahrenheit
    "1E-9 1/ft": "1/Gft",  # per thousand million foot
    "1E-6 acre.ft/bbl": "acre_foot/Mbbl",
    "1E-6 bbl/ft3": "bbl/Mcubic_foot",
    "1E-6 bbl/m3": "bbl/Mcubic_metre",
    "1E-6 gal[US]": "mugallon",
    "10 Mg/m3": "deca_mega_gram/m^3",
    "10 ft": "deca_ft",
    "10 in": "deca_in",
    "10 km": "deca_km",
    "10 kN": "ten_kilonewton",
    "30 ft": "thirty_ft",
    "30 m": "thirty_m",
    "100 ft": "hecto_ft",
    "100 km": "hecto_km",
    "100 ka[t]": "hundred_thousand_julian_year",
    "1000 m3/(h.m)": "kcubic_metre/(h.m)",  # (thousand cubic metre per hour) per metre
    "1000 lbf.ft": "klbf.ft",  # thousand foot pound-force
    "1000 ft3/(d.ft)": "kcubic_feet/(d.ft)",
    "1000 m3/(d.m)": "kcubic_metre/(d.m)",
    "1000 ft3/bbl": "kcubic_feet/bbl",
    "1000 m3/m3": "kcubic_metre/cubic_metre",  # thousand cubic metre per cubic metre
    "1000 ft3/(psi.d)": "kcubic_foot/(psi.d)",
    "1000 bbl.ft/d": "kbbl.ft/d",
    "1000 m4/d": "metre_to_power_four/d",
    "1000 bbl/d": "kbbl/d",
    "1000 ft3/d": "kcubic_foot/d",
    "1000 m3/d": "kcubic_metre/d",
    "1000 m3/h": "kcubic_metre/h",
    "1000 ft/h": "kft/h",
    "1000 ft/s": "kft/s",
    "1000 lbf/s2": "klbf/s^2",
    "1000 ft": "kilo_ft",
    "1000 bbl": "kbbl",
    "1000 ft3": "kcubic_foot",
    "1000 gal[UK]": "kUK_gallon",
    "1000 gal[US]": "kgallon",
    "1000 m3": "kcubic_metre",
    "1E6 ft3/(acre.ft)": "Mcubic_foot_per_acre_foot",
    "1E6 ft3/bbl": "Mcubic_foot_per_barrel",
    "1E6 bbl/d": "Mbarrel_per_day",
    "1E6 ft3/d": "Mcubic_foot_per_day",
    "1E6 m3/d": "Mcubic_metre_per_day",
    "1E6 Btu[IT]/h": "Mbtu_per_hour",
    "1E6 bbl/acre": "Mbarrel_per_acre",
    "1E6 acre.ft/bbl": "Macre_foot_per_barrel",
    "1E6 bbl/(acre.ft)": "Mbarrel_per_acre_foot",
    "1E6 Btu[IT]": "MBtu",
    "1E6 m3": "Mcubic_metre",
    "1E6 bbl": "Mbbl",
    "1E6 ft3": "Mcubic_foot",
    "1E6 (ft3/d)/(bbl/d)": "Mcubic_foot_per_day_per_barrel_per_day",
    "1E6 lbm/a": "Mlb/julian_year",
    "1E9 bbl": "Gbbl",
    "1E9 ft3": "Gcubic_foot",
    "1E12 ft3": "Tcubic_foot",
    #
    #
    "Euc": "Euc",
    "cEuc": "cEuc",
    "dEuc": "dEuc",
    "EEuc": "EEuc",
    "fEuc": "fEuc",
    "GEuc": "GEuc",
    "kEuc": "kEuc",
    "mEuc": "mEuc",
    "MEuc": "MEuc",
    "nEuc": "nEuc",
    "pEuc": "pEuc",
    "TEuc": "TEuc",
    "uEuc": "uEuc",
    "%[mass]": "percentage_mass",
    "ppm[mass]": "ppm_mass",
    "ppb[mass]": "ppb_mass",
    "%[area]": "percentage_area",
    "%[vol]": "percentage_vol",
    "ppm[vol]": "ppm_vol",
    "%[molar]": "percentage_molar",
    "lbmol": "lbmol",
    "lbmol/(h.ft2)": "lbmol/(h.ft^2)",
    "lbmol/(s.ft2)": "lbmol/(s.ft^2)",
    "lbmol/ft3": "lbmol/(ft^3)",
    "lbmol/gal[UK]": "lbmol/UK_gallon",
    "lbmol/gal[US]": "lbmol/gallon",
    "lbmol/h": "lbmol/h",
    "lbmol/s": "lbmol/s",
    "lbm/lbmol": "lb/lbmol",
    "Btu[UK]": "Btu_it",
    "Btu[IT]/(lbmol.deltaF)": "Btu_it/(lbmol.F)",
    "Btu[IT]/lbmol": "Btu_it/lbmol",
    "ft3/lbmol": "ft^3/lbmol",
    "sack[94lbm]": "sack",
    "kg/sack[94lbm]": "kg/sack",
    "ft3/sack[94lbm]": "ft^3/sack",
    "gal[US]/sack[94lbm]": "gallon/sack",
    "ft[US]": "us_survey_ft",
    "yd[US]": "us_survey_yard",
    "in[US]": "us_survey_in",
    "link[US]": "us_survey_link",
    "chain[US]": "us_survey_chain",
    "rod[US]": "us_survey_rod",
    "fur[US]": "us_survey_furlong",
    "mi[US]": "us_survey_mile",
    "tonRefrig": "refrigeration_ton",
    "kW/(m2.deltaK)": "kW/(m^2.K)",
    "kJ/(h.m2.deltaK)": "kJ/(h.m^2.K)",
    "W/(m3.deltaK)": "W/(m^3.K)",
    "Btu[IT]/(h.ft3.deltaF)": "Btu_it/(h.ft^3.F)",
    "Btu[IT]/(s.ft3.deltaF)": "Btu_it/(s.ft^3.F)",
    "kW/(m3.deltaK)": "kW/(m^3.K)",
    "W/(m2.deltaK)": "W/(m^2.K)",
    "Btu[IT]/(h.ft2.deltaF)": "Btu_it/(h.ft^2.F)",
    "Btu[IT]/(h.ft2.deltaR)": "Btu_it/(h.ft^2/degR)",
    "Btu[IT]/(h.m2.deltaC)": "Btu_it/(h.m^2.C)",
    "Btu[IT]/(s.ft2.deltaF)": "Btu_it/(s.ft^2.F)",
    "cal[th]/(h.cm2.deltaC)": "cal_th/(h.cm^2.C)",
    "cal[th]/(s.cm2.deltaC)": "cal_th/(s.cm^2.c)",
    "J/(s.m2.deltaC)": "J/(s.m^2.C)",
    "kcal[th]/(h.m2.deltaC)": "kcal_th/(h.m^2.C)",
    "1/deltaC": "1/C",
    "1/deltaF": "1/F",
    "1/deltaK": "1/K",
    "1/deltaR": "1/degR",
    "m3/rev": "m^3/revolution",
    "J.m/(s.m2.deltaK)": "J.m/(s.m^2.K)",
    "W/(m.deltaK)": "W/(m.K)",
    "Btu[IT].in/(h.ft2.deltaF)": "Btu_it.in/(h.ft^2.F)",
    "kJ.m/(h.m2.deltaK)": "kJ.m/(h.m^2.K)",
    "Btu[IT]/(h.ft.deltaF)": "Btu_it/(h.ft.F)",
    "cal[th]/(h.cm.deltaC)": "cal_th/(h.cm.C)",
    "cal[th]/(s.cm.deltaC)": "cal_th/(s.cm.C)",
    "kcal[th]/(h.m.deltaC)": "kcal_th/(h.m.C)",
    "cal[th]/(mol.deltaC)": "cal_th/(mol.C)",
    "kJ/(kmol.deltaK)": "kJ/(kmol.K)",
    "J/deltaK": "J/K",
    "W/deltaK": "W/K",
    "kcal[th]/mol": "kcal_th/mol",
    "Btu[IT]": "Btu_it",
    "Btu[th]": "Btu_th",
    "cal[IT]": "cal_it",
    "cal[th]": "cal_th",
    "therm[EC]": "EC_therm",
    "therm[UK]": "therm",
    "therm[US]": "US_therm",
    "hp[metric].h": "metric_horsepower.h",
    "gal[UK]/(h.ft)": "UK_gallon/(h.ft)",
    "gal[UK]/(h.in)": "UK_gallon/(h.in)",
    "gal[UK]/(min.ft)": "UK_gallon/(min.ft)",
    "gal[US]/(h.ft)": "gallon/(h.ft)",
    "gal[US]/(h.in)": "gallon/(h.in)",
    "gal[US]/(min.ft)": "gallon/(min.ft)",
    "m3/(d.m)": "m^3/(d.m)",
    "m3/(h.m)": "M^3/(h.m)",
    "m3/(s.ft)": "m^3/(s.ft)",
    "Btu[IT]/lbm": "Btu_it/lb",
    "cal[th]/g": "cal_th/g",
    "cal[th]/kg": "cal_th/kg",
    "cal[th]/lbm": "cal_th/lb",
    "hp.h/lbm": "hp.h/lb",
    "kcal[th]/g": "kcal_th/g",
    "kcal[th]/kg": "kcal_th/kg",
    "lbf.ft/lbm": "lbf.ft/lb",
    "kg.m2": "kg.m^2",
    "lbm.ft2": "lb.ft^2",
    "J/(mol.deltaK)": "J/(mol.K)",
    "J/(kg.deltaK)": "J/(kg.K)",
    "Btu[IT]/(lbm.deltaF)": "Btu_it/(lb.F)",
    "Btu[IT]/(lbm.deltaR)": "Btu_it/(lb.degR)",
    "cal[th]/(g.deltaK)": "cal_th/(g.K)",
    "J/(g.deltaK)": "J/(g.K)",
    "kcal[th]/(kg.deltaC)": "kcal_th/(kg.C)",
    "kJ/(kg.deltaK)": "kJ/(kg.K)",
    "kW.h/(kg.deltaC)": "kW.h/(kg.C)",
    "W.m2.deltaK/(J.deltaK)": "W.m^2.K/(J.K)",
    "ft3/ft2": "ft^3/ft^2",
    "m/deltaK": "m/K",
    "ft/deltaF": "m/F",
    "m3/(s.m2)": "m^3/(s.m^2)",
    "ft3/(min.ft2)": "ft^3/(min.ft^2)",
    "ft3/(s.ft2)": "ft^3/(s.ft^2)",
    "gal[UK]/(h.ft2)": "UK_gallon/(h.ft^2)",
    "gal[UK]/(h.in2)": "UK_gallon/(h.in^2)",
    "gal[UK]/(min.ft2)": "UK_gallon/(min.ft^2)",
    "gal[US]/(h.ft2)": "gallon/(h.ft^2)",
    "gal[US]/(h.in2)": "gallon/(h.in^2)",
    "gal[US]/(min.ft2)": "gallon/(min.ft^2)",
    "ton[US]/min": "short_ton/minute",
    "ton[US]/h": "short_ton/hour",
    "ton[US]/d": "short_ton/day",
    "ton[US]/a": "short_ton/julian_year",  # US ton-mass per julian year
    "ton[UK]/min": "long_ton/minute",
    "ton[UK]/h": "long_ton/hour",
    "ton[UK]/d": "long_ton/day",
    "ton[UK]/a": "long_ton/julian_year",  # UK ton-mass per julian year
    "ton[US]/ft3": "short_ton/m^3",
    "tonf[UK]/ft": "long_ton_force/ft",
    "tonf[US]/ft": "short_ton_force/ft",
    "tonf[US]/in2": "short_ton_force/in^2",
    "tonf[US]/ft2": "short_ton_force/ft^2",
    "tonf[UK]/ft2": "long_ton_force/ft^2",
    "tonf[US].mi/bbl": "short_ton_force.mile/bbl",
    "m3/m2": "m3_per_m2",
    "deltaF/s": "F/s",
    "deltaK/s": "K/s",
    "deltaC/kPa": "c/kPa",
    "deltaF/psi": "F/psi",
    "deltaK/Pa": "K/Pa",
    "deltaK/W": "K/W",
    "deltaC.m2.h/kcal[th]": "C.m^2.h/kcal_th",
    "deltaF.ft2.h/Btu[IT]": "F.ft^2.h/Btu_it",
    "deltaK.m2/kW": "K.m^2/kW",
    "deltaK.m2/W": "K.m^2/W",
    "A/cm2": "A/cm^2",
    "A/ft2": "A/ft^2",
    "A/mm2": "A/mm^2",
    "mA/cm2": "mA/cm^2",
    "mA/ft2": "ma/ft^2",
    "uA/cm2": "uA/cm^2",
    "uA/in2": "uA/in^2",
    "A/m2": "A/m^2",
    "wk": "week",
    "1/wk": "1/week",
    "mila": "milliarcsecond",
    "mina": "arc_minute",
    "rev": "revolution",
    "seca": "arc_second",
    "dega/ft": "deg/ft",
    "dega/m": "deg/m",
    "rev/ft": "revolution/ft",
    "rev/m": "revolution/minute",
    "rad/m3": "radian/m^3",
    "rad/ft3": "radian/ft^3",
    "dega/h": "degree/hour",
    "dega/min": "degree/minute",
    "dega/s": "degree/second",
    "rev/s": "revolution/second",
    "rad/s2": "radian/second^2",
    "deltaF": "F",
    "deltaR": "degR",
    "deltaK": "K",
    "ccr": "centisimal_minute",
    "ccgr": "centisimal_second",
    "oz t/ton[US]": "troy_ounce/short_ton",
    "in/(in.deltaF)": "in/(in.F)",
    "A.m2": "A.m^2",
    "C/cm2": "C/cm^2",
    "C/mm2": "C/mm^2",
    "mC/m2": "mC/m^2",
    "C/m2": "C/m^2",
    "A.s/m3": "A.s/m^3",
    "C/cm3": "c/cm^3",
    "C/mm3": "C/mm^3",
    "C/m3": "C/m^3",
    "cd/m2": "cd/m^2",
    "deltaC/ft": "C/ft",
    "deltaC/hm": "C/hm",
    "deltaC/km": "C/km",
    "deltaC/m": "C/m",
    "deltaF/ft": "F/ft",
    "deltaF/m": "F/m",
    "deltaK/km": "K/km",
    "deltaK/m": "K/m",
    "deltaC/h": "C/h",
    "deltaC/min": "C/min",
    "deltaC/s": "C/s",
    "deltaF/h": "F/h",
    "deltaF/min": "F/min",
    "Btu[IT]/(hp.h)": "Btu_it/(hp.h)",
    "m/(m.deltaK)": "m/(m.K)",
    "m3/(m3.deltaK)": "m^3/(m^3.K)",
    "mm/(mm.deltaK)": "mm/(mm.K)",
    "ppm[vol]/deltaC": "ppm/C",
    "tonf[US].ft": "short_ton_force.ft",
    "mi[US]2": "mile^2",
    "tonf[US].mi": "short_ton_force.mi",
    "ppm[vol]/deltaF": "ppm/F",
    "deltaC": "C",
    "a[t]": "julian_year",
    "Ea[t]": "Ejulian_year",
    "Ga[t]": "Gjulian_year",
    "ka[t]": "kjulian_year",
    "Ma[t]": "Mjulian_year",
    "Ta[t]": "Tjulian_year",
    "ft3/(d.ft)": "ft^3/(d.ft)",
    "ft/lbm": "ft/lb",
    "cm2/s": "cm^2/s",
    "ft2/h": "ft^2/h",
    "ft2/s": "ft^2/s",
    "in2/s": "in^2/s",
    "m2/d": "m^2/d",
    "m2/h": "m^2/h",
    "mm2/s": "mm^2/s",
    "m/s2": "m/s^2",
    "cm/s2": "cm/s^2",
    "ft/s2": "ft/s^2",
    "in/s2": "in/s^2",
    "dm3/m": "dm^3/m",
    "ft3/ft": "ft^3/ft",
    "gal[UK]/mi": "UK_gallon/mi",
    "gal[US]/ft": "gallon/ft",
    "gal[US]/mi": "gallon/mi",
    "in3/ft": "in^3/ft",
    "m3/km": "m^3/km",
    "m2": "m^2",
    "ft2": "ft^2",
    "mi2": "mi^2",
    "yd2": "yd^2",
    "m2/kg": "m^2/kg",
    "cm2/g": "cm^2/g",
    "ft2/lbm": "ft^2/lb",
    "m2/g": "m^2/g",
    "m2/mol": "m^2/mol",
    "m2/s": "m^2/s",
    "m3/(s.m)": "m^3/(s.m)",
    "mol.m2/(mol.s)": "mol.m^2/(mol.s)",
    "Pa.s.m3/kg": "Ps.s.m^3/kg",
    "footcandle": "lm/ft^2",
    "lm/m2": "lm/m^2",
    "footcandle.s": "(lm/ft^2).s",
    "gal[UK]/ft3": "UK_gallon/ft^3",
    "gal[US]/bbl": "gallon/bbl",
    "gal[US]/ft3": "gallon/ft^3",
    "L/m3": "L/m^3",
    "m3/(ha.m)": "m^3/(ha.m)",
    "m3/bbl": "m^3/bbl",
    "mL/gal[UK]": "mL/UK_gallon",
    "mL/gal[US]": "mL/gallon",
    "b/cm3": "b/cm^3",
    "ft2/in3": "ft^2/in^3",
    "m2/cm3": "m^2/cm^3",
    "m2/m3": "m^2/m^3",
    "1/ft2": "1/ft^2",
    "1/km2": "1/km^2",
    "1/mi2": "1/mi^2",
    "1/m2": "1/m^2",
    "m/m3": "m/m^3",
    "ft/ft3": "ft/ft^3",
    "ft/gal[US]": "ft/gallon",
    "1/gal[UK]": "1/UK_gallon",
    "1/gal[US]": "1/gallon",
    "km/dm3": "km/dm^3",
    "1/ft3": "1/ft^3",
    "1/m3": "1/m^3",
    "1/lbm": "1/lb",
    "mi/gal[UK]": "mi/UK_gallon",
    "mi/gal[US]": "mi/gallon",
    "m3/m": "m^3/m",
    "cm2": "cm^2",
    "km2": "km^2",
    "mm2": "mm^2",
    "um2": "um^2",
    "dega": "degree",
    "inH2O[60degF]": "inch_H2O_60F",
    "inHg[32degF]": "inch_Hg_32F",
    "inHg[60degF]": "inch_Hg_60F",
    "ton[US]/ft2": "short_ton/ft^2",
    "lbm.ft2/s2": "lb.ft^2/s^2",
    "hp[elec]": "electrical_horsepower",
    "hp[hyd]": "hydraulic_horsepower",
    "hp[metric]": "metric_horsepower",
    "ccal[th]": "ccal_th",
    "dcal[th]": "dcal_th",
    "Ecal[th]": "Ecal_th",
    "fcal[th]": "fcal_th",
    "Gcal[th]": "Gcal_th",
    "kcal[th]": "kcal_th",
    "mcal[th]": "mcal_th",
    "Mcal[th]": "Mcal_th",
    "ncal[th]": "ncal_th",
    "pcal[th]": "pcal_th",
    "Tcal[th]": "Tcal_th",
    "ucal[th]": "ucal_th",
    "Btu[IT]/h": "Btu_it/h",
    "Btu[IT]/min": "Btu_it/min",
    "Btu[IT]/s": "Btu_it/s",
    "cal[th]/h": "cal/h",
    "kcal[th]/h": "kcal/h",
    "ucal[th]/s": "ucal/h",
    "floz[UK]": "UK_fluid_ounce",
    "floz[US]": "fluid_ounce",
    "gal[UK]": "UK_gallon",
    "gal[US]": "gallon",
    "pt[UK]": "UK_pint",
    "pt[US]": "pint",
    "qt[UK]": "UK_quart",
    "qt[US]": "quart",
    "cm3": "cm^3",
    "dm3": "dm^3",
    "km3": "km^3",
    "mm3": "mm^3",
    "um2.m": "um^2.m",
    "m3": "m^3",
    "ft3": "ft^3",
    "in3": "in^3",
    "mi3": "mi^3",
    "yd3": "yd^3",
    "m3/rad": "m^3/rad",
    "ft3/rad": "ft^3/rad",
    "m3/kg": "m^3/kg",
    "bbl/ton[UK]": "bbl/long_ton",
    "bbl/ton[US]": "bbl/short_ton",
    "cm3/g": "cm^3/g",
    "dm3/kg": "dm^3/kg",
    "dm3/t": "dm^3/t",
    "ft3/kg": "ft^3/kg",
    "ft3/lbm": "ft^3/lb",
    "gal[UK]/lbm": "UK_gallon/lb",
    "gal[US]/lbm": "gallon/lb",
    "gal[US]/ton[UK]": "gallon/long_ton",
    "gal[US]/ton[US]": "gallon/short_ton",
    "L/ton[UK]": "L/long_ton",
    "m3/g": "m^3/g",
    "m3/t": "m^3/t",
    "m3/ton[UK]": "m^3/long_ton",
    "m3/ton[US]": "m^3/short_ton",
    "m3/mol": "m^3/mol",
    "dm3/kmol": "dm^3/kmol",
    "m3/kmol": "m^3/kmol",
    "m3/s": "m^3/s",
    "cm3/h": "cm^3/h",
    "cm3/min": "cm^3/min",
    "cm3/s": "cm^3/s",
    "dm3/s": "dm^3/s",
    "ft3/d": "ft^3/d",
    "ft3/h": "ft^3/h",
    "ft3/min": "ft^3/min",
    "ft3/s": "ft^3/s",
    "gal[UK]/d": "UK_gallon/d",
    "gal[UK]/h": "UK_gallon/h",
    "gal[UK]/min": "UK_gallon/min",
    "gal[US]/d": "gallon/d",
    "gal[US]/h": "gallon/h",
    "gal[US]/min": "gallon/min",
    "m3/d": "m^3/d",
    "m3/h": "m^3/h",
    "m3/min": "m^3/min",
    "m3/s2": "m^3/s^2",
    "bbl/d2": "bbl/d^2",
    "bbl/h2": "bbl/h^2",
    "dm3/s2": "dm^3/s^2",
    "ft3/d2": "ft^3/d^2",
    "ft3/h2": "ft^3/h^2",
    "ft3/min2": "ft^3/min^2",
    "ft3/s2": "ft^3/s^2",
    "gal[UK]/h2": "UK_gallon/h^2",
    "gal[UK]/min2": "UK_gallon/min^2",
    "gal[US]/h2": "gallon/h^2",
    "gal[US]/min2": "gallon/min^2",
    "L/s2": "L/s^2",
    "m3/d2": "m^3/d^2",
    "nohm.mil2/ft": "nohm.mil^2/ft",
    "nohm.mm2/m": "nohm.mm^2/m",
    "ohm.m2/m": "ohm.m^2/m",
    "N.m2": "N.m^2",
    "dyne.cm2": "dyne.cm^2",
    "kgf.m2": "kg.m^2",
    "kN.m2": "kN.m^2",
    "lbf.in2": "lbf.in^2",
    "mN.m2": "mN.m^2",
    "pdl.cm2": "pdl.cm^2",
    "tonf[UK].ft2": "long_ton_force.ft^2",
    "tonf[US].ft2": "short_ton_force.ft^2",
    "m2/(Pa.s)": "m^2/(Pa.s)",
    "ft3/(ft.psi.d)": "ft^3/(ft.psi.d)",
    "m2/(kPa.d)": "m^2/(kPa.d)",
    "mD.ft2/(lbf.s)": "mD.ft^2/(lbf.s)",
    "mD.in2/(lbf.s)": "mD.in^2/(lbf.s)",
    "cm4": "cm^4",
    "m4": "m^4",
    "in4": "in^4",
    "m4/s": "m^4/s",
    "m3/(Pa.s)": "m^3/(Pa.s)",
    "m3/(bar.d)": "m^3/(bar.d)",
    "m3/(bar.h)": "m^3/(bar.h)",
    "m3/(bar.min)": "m^3/(bar.min)",
    "m3/(kPa.d)": "m^3/(kPa.d)",
    "m3/(kPa.h)": "m^3/(kPa.h)",
    "m3/(psi.d)": "m^3/(psi.d)",
    "m3/Pa": "m^3/Pa",
    "m3/kPa": "m^3/kPa",
    "lbm.ft": "lb.ft",
    "lbm.ft/s": "lb.ft/s",
    "J.m/m2": "J.m/m^2",
    "kcal[th].m/cm2": "kcal_th.m/cm^2",
    "ton[US]": "short_ton",
    "ton[UK]": "long_ton",
    "kton[US]": "kshort_ton",
    "kton[UK]": "kshort_ton",
    "tonf[US]": "short_ton_force",
    "tonf[UK]": "long_ton_force",
    "Mton[US]": "Mshort_ton",
    "Mton[UK]": "Mlong_ton",
    "tonf[US].mi/ft": "short_ton_force.mi/ft",
    "m3/J": "m^3/J",
    "dm3/(kW.h)": "dm^3/(kW.h)",
    "dm3/MJ": "dm^3/MJ",
    "m3/(kW.h)": "m^3/(kW.h)",
    "mm3/J": "mm^3/J",
    "ozm[troy]": "troy_ounce",
    "1000 ct": "kct",
    "1000 ozm[troy]": "ktroy_ounce",
    "1000000 ozm": "Moz",
    "1000000 ozm[troy]": "Mtroy_ounce",
    "cwt[US]": "cwt",
    "cwt[UK]": "UK_cwt",
    "pt[UK]/(hp.h)": "UK_pint/(hp.h)",
    "ozm": "oz",
    "lbm": "lb",
    "klbm": "klb",
    "Mlbm": "Mlb",
    "kg.m/cm2": "kg.m/cm^2",
    "klbm/in": "klb/in",
    "lbm/ft": "lb/ft",
    "kg/m2": "kg/m^2",
    "lbm/ft2": "lb/ft^2",
    "Mg/m2": "Mg/m^2",
    "kg/(m2.s)": "kg/(m^2.s)",
    "g.ft/(cm3.s)": "g.ft/(cm^3.s)",
    "g.m/(cm3.s)": "g.m/(cm^3.s)",
    "lbm/(ft2.s)": "lb(ft^2.s)",
    "lbm/(ft2.h)": "lb(ft^2.h)",
    "cm3/m3": "cm^3/m^3",
    "dm3/m3": "dm^3/m^3",
    "ft3/bbl": "ft^3/bbl",
    "bbl/ft3": "bbl/ft^3",
    "bbl/m3": "bbl/m^3",
    "cm3/L": "cm^3/L",
    "N/m3": "N/m^3",
    "lbf/gal[US]": "lbf/gallon",
    "lbf/ft3": "lbf/ft^3",
    "g/cm3": "g/cm^3",
    "g/dm3": "g/dm^3",
    "g/gal[UK]": "g/UK_gallon",
    "g/gal[US]": "g/gallon",
    "grain/ft3": "grain/ft^3",
    "grain/gal[US]": "grain/gallon",
    "lbm/bbl": "lb/bbl",
    "lbm/ft3": "lb/ft^3",
    "lbm/gal[UK]": "lb/UK_gallon",
    "lbm/gal[US]": "lb/gallon",
    "lbm/in3": "lb/in^3",
    "kg/dm3": "kg/dm^3",
    "mg/dm3": "mg/dm^3",
    "mg/gal[US]": "mg/gallon",
    "Mg/m3": "Mg/m^3",
    "kg/m3": "kg/m^3",
    "g/m3": "g/m^3",
    "mg/m3": "mg/m^3",
    "t/m3": "t/m^3",
    "ug/cm3": "ug/cm^3",
    "kg/m4": "kg/m^4",
    "g/cm4": "g/cm^4",
    "kg/dm4": "kg/dm^4",
    "lbm/(gal[UK].ft)": "lb/(UK_gallon.ft)",
    "lbm/(gal[US].ft)": "lb/(gallon.ft)",
    "lbm/ft4": "lb/ft^4",
    "Pa.s2/m3": "Pa.s^2/m^3",
    "Pa.s/m3": "Pa.s/m^3",
    "Pa/m3": "Pa/m^3",
    "psi2.d/(cP.ft3)": "psi^2.d/(cP.ft^3)",
    "lbm/(ft.h)": "lb/(ft.h)",
    "lbm/(ft.s)": "lb/(ft.s)",
    "dyne.s/cm2": "dyne.s/cm^2",
    "kgf.s/m2": "kgf.s/m^2",
    "lbf.s/ft2": "lbf.s/ft^2",
    "lbf.s/in2": "lbf.s/in^2",
    "N.s/m2": "N.s/m^2",
    "J/m3": "J/m^3",
    "Btu[IT]/bbl": "Btu_it/bbl",
    "Btu[IT]/ft3": "Btu_it/ft^3",
    "Btu[IT]/gal[UK]": "Btu_it/UK_gallon",
    "Btu[IT]/gal[US]": "Btu_it/gallon",
    "cal[th]/cm3": "cal_th/cm^3",
    "cal[th]/mL": "cal_th/mL",
    "cal[th]/mm3": "cal_th/mm^3",
    "erg/m3": "erg/m^3",
    "erg/cm3": "erg/cm^3",
    "J/dm3": "J/dm^3",
    "kcal[th]/m3": "kcal_th/m^3",
    "kcal[th]/cm3": "kcal_th/cm^3",
    "kJ/dm3": "kJ/dm^3",
    "kJ/m3": "kJ/m^3",
    "kW.h/dm3": "kW.h/dm^3",
    "kW.h/m3": "kW.h/m^3",
    "lbf.ft/gal[US]": "lbf.ft/gallon",
    "MJ/m3": "MJ/m^3",
    "MW.h/m3": "MW.h/m^3",
    "dyne/cm2": "dyne/cm^2",
    "kgf/m2": "kgf/m^2",
    "kgf/cm2": "kgf/cm^2",
    "kgf/mm2": "kgf/mm^2",
    "kN/m2": "kN/m^2",
    "lbf/ft2": "lbf/ft^2",
    "N/m2": "N/m^2",
    "N/mm2": "N/mm^2",
    "Pa2/(Pa.s)": "Pa^2/(Pa.s)",
    "W/m3": "W/m^3",
    "bar2/cP": "bar^2/cP",
    "kPa2/cP": "kPa^2/cP",
    "psi2/cP": "psi^2/cP",
    "Btu[IT]/(h.ft3)": "Btu_it/(h.ft^3)",
    "Btu[IT]/(s.ft3)": "Btu_it/(s.ft^3)",
    "cal[th]/(h.cm3)": "cal_th/(h.cm^3)",
    "cal[th]/(s.cm3)": "cal_th/(s.cm^3)",
    "hp/ft3": "hp/ft^3",
    "kW/m3": "kW/m^3",
    "uW/m3": "uW/m^3",
    "W/(m2.sr)": "W/(m^2.sr)",
    "lbm/s": "lb/s",
    "lbm/min": "lb/min",
    "lbm/h": "lb/h",
    "lbm/d": "lb/d",
    "J/m2": "J/m^2",
    "erg/cm2": "erg/cm^2",
    "J/cm2": "J/cm^2",
    "kgf.m/cm2": "kgf.m/cm^2",
    "lbf.ft/in2": "lbf.ft/in^2",
    "mJ/cm2": "mJ/cm^2",
    "mJ/m2": "mJ/m^2",
    "Btu[IT]/(h.ft2)": "Btu_it/(h.ft^2)",
    "Btu[IT]/(s.ft2)": "Btu_it/(s.ft^2)",
    "cal[th]/(h.cm2)": "cal_th/(h.cm^2)",
    "hp/in2": "hp/in^2",
    "hp[hyd]/in2": "hp/in^2",
    "kW/cm2": "kW/cm^2",
    "kW/m2": "kW/m^2",
    "mW/m2": "mW/m^2",
    "ucal[th]/(s.cm2)": "ucal_th/(s.cm^2)",
    "W/m2": "W/m^2",
    "W/cm2": "W/cm^2",
    "W/mm2": "W/mm^2",
    "GPa2": "GPa^2",
    "at": "at",
    "kPa2": "kPa^2",
    "kpsi2": "kpsi^2",
    "in2/ft2": "in^2/ft^2",
    "in2": "in^2",
    "Pa2": "Pa^2",
    "bar2": "bar^2",
    "psi2": "psi^2",
    "mol/m2": "mol/m^2",
    "mol/(s.m2)": "mol/(s.m^2)",
    "mol/m3": "mol/m^3",
    "kmol/m3": "kmol/m^3",
    "s/m3": "s/m^3",
    "d/ft3": "d/ft^3",
    "d/m3": "d/m^3",
    "h/ft3": "h/ft^3",
    "h/m3": "h/m^3",
    "s/ft3": "s/ft^3",
    "s/qt[UK]": "s/UK_quart",
    "s/qt[US]": "s/quart",
    "lbm/(hp.h)": "lb/(hp.h)",
}

_registry = pint.get_application_registry()
RESOURCE_PATH = Path(__file__).parent
EVO_UNITS = RESOURCE_PATH / "evo_units.txt"
_registry.load_definitions(EVO_UNITS)

# build the look up table mapping Pint units
# to the corresponding Unit_V1_0_1 enumeration value
_pint_lookup: dict[str, Unit] = dict()
for e in typing.get_args(Unit):
    for p in e:
        try:
            name = p.value
            if name in _translation_table:
                name = _translation_table[name]
                if name is None:
                    continue
            pn = str(_registry.Quantity(1, name).units)
            _pint_lookup[pn] = p
        except Exception as e:
            logger.warning(f"Unable to map {p.value} to pint type {e}")
