#  Copyright © 2025 Bentley Systems, Incorporated
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

import typing

from evo_schemas.elements import Unit_V1_0_1 as Unit
from pint.errors import UndefinedUnitError
from pint_pandas import PintType

import evo.logging

logger = evo.logging.getLogger("data_converters")


class UnitMapper:
    """Map units between Pint and EVO"""

    @staticmethod
    def lookup(pt: PintType) -> Unit | None:
        """Map a PintType to it's corresponding Evo Unit"""
        units = pt.units
        key = str(units)
        return _pint_lookup.get(key, None)


# table mapping Evo Unit_V1_0_1 values to the
# corresponding Pint Unit string value:
#
# NOTE: This table is incomplete, any entry with a value of None needs to have a pint value
#       assigned.
#       See https://raw.githubusercontent.com/hgrecco/pint/refs/heads/master/pint/default_en.txt
#       for details of pint units.
_translation_table: dict[str, str] = {
    "Euc": None,
    "cEuc": None,
    "dEuc": None,
    "EEuc": None,
    "fEuc": None,
    "GEuc": None,
    "kEuc": None,
    "mEuc": None,
    "MEuc": None,
    "nEuc": None,
    "pEuc": None,
    "TEuc": None,
    "uEuc": None,
    "1/deltaC": None,
    "1/deltaF": None,
    "1/deltaK": None,
    "1/deltaR": None,
    "%[mass]": None,
    "ppm[mass]": None,
    "ppb[mass]": None,
    "%[area]": None,
    "%[vol]": None,
    "ppm[vol]": None,
    "%[molar]": None,
    "kg/sack[94lbm]": None,
    "ton[US]/min": None,
    "ton[US]/h": None,
    "ton[US]/d": None,
    "ton[US]/a": None,
    "ton[UK]/min": None,
    "ton[UK]/h": None,
    "ton[UK]/d": None,
    "ton[UK]/a": None,
    "ton[US]/ft3": None,
    "tonf[UK]/ft": None,
    "tonf[US]/ft": None,
    "tonf[US]/in2": None,
    "tonf[US]/ft2": None,
    "tonf[UK]/ft2": None,
    "tonf[US].mi/bbl": None,
    "lbmol": None,
    "lbmol/(h.ft2)": None,
    "lbmol/(s.ft2)": None,
    "lbmol/ft3": None,
    "lbmol/gal[UK]": None,
    "lbmol/gal[US]": None,
    "lbmol/h": None,
    "lbmol/s": None,
    "at": None,
    "wk": None,
    "a[t]": None,
    "Ea[t]": None,
    "Ga[t]": None,
    "ka[t]": None,
    "Ma[t]": None,
    "Ta[t]": None,
    "dAPI": None,
    "gAPI": None,
    "nAPI": None,
    "O": None,
    "dB/O": None,
    "B/O": None,
    "lbm/lbmol": None,
    "kW/(m2.deltaK)": None,
    "kJ/(h.m2.deltaK)": None,
    "W/(m3.deltaK)": None,
    "Btu[IT]/(h.ft3.deltaF)": None,
    "Btu[IT]/(s.ft3.deltaF)": None,
    "kW/(m3.deltaK)": None,
    "W/(m2.deltaK)": None,
    "Btu[IT]/(h.ft2.deltaF)": None,
    "Btu[IT]/(h.ft2.deltaR)": None,
    "Btu[IT]/(h.m2.deltaC)": None,
    "Btu[IT]/(s.ft2.deltaF)": None,
    "cal[th]/(h.cm2.deltaC)": None,
    "cal[th]/(s.cm2.deltaC)": None,
    "J/(s.m2.deltaC)": None,
    "kcal[th]/(h.m2.deltaC)": None,
    "sack[94lbm]": None,
    "J.m/(s.m2.deltaK)": None,
    "W/(m.deltaK)": None,
    "Btu[IT].in/(h.ft2.deltaF)": None,
    "kJ.m/(h.m2.deltaK)": None,
    "Btu[IT]/(h.ft.deltaF)": None,
    "cal[th]/(h.cm.deltaC)": None,
    "cal[th]/(s.cm.deltaC)": None,
    "kcal[th]/(h.m.deltaC)": None,
    "TD[API]/(Pa.s)": None,
    "ft3/sack[94lbm]": None,
    "gal[US]/sack[94lbm]": None,
    "ft3/lbmol": None,
    "TD[API].m": None,
    "m3/rev": None,
    "tonRefrig": None,
    "tonf[US].ft": None,
    "tonf[US].mi": None,
    "cmH2O[4degC]": None,
    "inH2O[32degF]": None,
    "inH2O[39degF]": None,
    "mmHg[0degC]": None,
    "umHg[0degC]": None,
    "1000 m3/(h.m)": None,
    "gal[UK]/(h.ft)": None,
    "gal[UK]/(h.in)": None,
    "gal[UK]/(min.ft)": None,
    "gal[US]/(h.ft)": None,
    "gal[US]/(h.in)": None,
    "gal[US]/(min.ft)": None,
    "m3/(d.m)": None,
    "m3/(h.m)": None,
    "m3/(s.ft)": None,
    "Btu[IT]/lbm": None,
    "cal[th]/g": None,
    "cal[th]/kg": None,
    "cal[th]/lbm": None,
    "hp.h/lbm": None,
    "kcal[th]/g": None,
    "kcal[th]/kg": None,
    "lbf.ft/lbm": None,
    "kg.m2": None,
    "lbm.ft2": None,
    "J/(mol.deltaK)": None,
    "Btu[IT]/(lbmol.deltaF)": None,
    "cal[th]/(mol.deltaC)": None,
    "kJ/(kmol.deltaK)": None,
    "J/deltaK": None,
    "W/deltaK": None,
    "Btu[IT]/lbmol": None,
    "kcal[th]/mol": None,
    "Btu[IT]": None,
    "Btu[th]": None,
    "Btu[UK]": None,
    "cal[IT]": None,
    "cal[th]": None,
    "therm[EC]": None,
    "therm[UK]": None,
    "therm[US]": None,
    "hp[metric].h": None,
    "1000 lbf.ft": None,
    "0.01 dm3/km": None,
    "0.01 L/km": None,
    "J/(kg.deltaK)": None,
    "Btu[IT]/(lbm.deltaF)": None,
    "Btu[IT]/(lbm.deltaR)": None,
    "cal[th]/(g.deltaK)": None,
    "J/(g.deltaK)": None,
    "kcal[th]/(kg.deltaC)": None,
    "kJ/(kg.deltaK)": None,
    "kW.h/(kg.deltaC)": None,
    "W.m2.deltaK/(J.deltaK)": None,
    "1000 ft3/(d.ft)": None,
    "1000 m3/(d.m)": None,
    "10 kN": None,
    "1000 ct": None,
    "1000 ozm[troy]": None,
    "1000000 ozm": None,
    "1000000 ozm[troy]": None,
    "1E6 (ft3/d)/(bbl/d)": None,
    "0.01 ft/ft": None,
    "1/30 m/m": None,
    "0.001 kPa2/cP": None,
    "0.001 bbl/ft3": None,
    "0.001 bbl/m3": None,
    "0.001 gal[UK]/bbl": None,
    "0.001 gal[UK]/gal[UK]": None,
    "0.001 gal[US]/bbl": None,
    "0.001 gal[US]/ft3": None,
    "0.001 gal[US]/gal[US]": None,
    "0.001 pt[US]/bbl": None,
    "0.001 pt[UK]/bbl": None,
    ".001 pt[US]/bbl": None,
    ".001 pt[UK]/bbl": None,
    "0.01 bbl/bbl": None,
    "0.1 gal[US]/bbl": None,
    "0.1 L/bbl": None,
    "0.1 pt[US]/bbl": None,
    "0.01 lbf/ft": None,
    "0.01 lbf/ft2": None,
    "1000 ft3/bbl": None,
    "1E6 acre.ft/bbl": None,
    "1E6 bbl/(acre.ft)": None,
    "1/30 lbf/m": None,
    "1/30 N/m": None,
    "1/2 ms": None,
    "100 ka[t]": None,
    "0.001 d/ft3": None,
    "0.001 h/ft": None,
    "0.001 d/ft": None,
    "1E6 lbm/a": None,
    "10 Mg/m3": None,
    "0.1 lbm/bbl": None,
    "0.01 grain/ft3": None,
    "0.001 lbm/gal[US]": None,
    "0.001 lbm/gal[UK]": None,
    "0.001 lbm/bbl": None,
    "0.001 psi/ft": None,
    "0.01 psi/ft": None,
    "1E-6 acre.ft/bbl": None,
    "1E-6 bbl/ft3": None,
    "1E-6 bbl/m3": None,
    "1E6 ft3/(acre.ft)": None,
    "1E6 ft3/bbl": None,
    "0.01 lbm/ft2": None,
    "1000 ft3/(psi.d)": None,
    "1000 bbl.ft/d": None,
    "1000 m4/d": None,
    "1/30 cm3/min": None,
    "1000 bbl/d": None,
    "1000 ft3/d": None,
    "1000 m3/d": None,
    "1000 m3/h": None,
    "1E6 bbl/d": None,
    "1E6 ft3/d": None,
    "1E6 m3/d": None,
    "0.01 L/kg": None,
    "1000 bbl": None,
    "1000 ft3": None,
    "1000 gal[UK]": None,
    "1000 gal[US]": None,
    "1000 m3": None,
    "1E12 ft3": None,
    "1E6 bbl": None,
    "1E6 ft3": None,
    "1E-6 gal[US]": None,
    "1E6 m3": None,
    "1E9 bbl": None,
    "1E9 ft3": None,
    "1E6 Btu[IT]/h": None,
    "1E6 Btu[IT]": None,
    "1000 lbf/s2": None,
    "1/16 in": None,
    "1/2 ft": None,
    "1/32 in": None,
    "1/64 in": None,
    "10 ft": None,
    "10 in": None,
    "10 km": None,
    "100 ft": None,
    "100 km": None,
    "1000 ft": None,
    "30 ft": None,
    "30 m": None,
    "1E6 bbl/acre": None,
    "ft3/ft2": None,
    "m/deltaK": None,
    "ft/deltaF": None,
    "m3/(s.m2)": None,
    "1000 ft/h": None,
    "1000 ft/s": None,
    "ft3/(min.ft2)": None,
    "ft3/(s.ft2)": None,
    "gal[UK]/(h.ft2)": None,
    "gal[UK]/(h.in2)": None,
    "gal[UK]/(min.ft2)": None,
    "gal[US]/(h.ft2)": None,
    "gal[US]/(h.in2)": None,
    "gal[US]/(min.ft2)": None,
    "gn": None,
    "mgn": None,
    "TD[API]": None,
    "D[API]": None,
    "ft[BnA]": None,
    "ft[BnB]": None,
    "ft[Br36]": None,
    "ft[Br65]": None,
    "ft[Cla]": None,
    "ft[GC]": None,
    "ft[Ind]": None,
    "ft[Ind37]": None,
    "ft[Ind62]": None,
    "ft[Ind75]": None,
    "ft[Se]": None,
    "ft[SeT]": None,
    "ft[US]": None,
    "fur[US]": None,
    "in[US]": None,
    "link[BnA]": None,
    "link[BnB]": None,
    "link[Cla]": None,
    "link[Se]": None,
    "link[SeT]": None,
    "link[US]": None,
    "m[Ger]": None,
    "mi[naut]": None,
    "mi[nautUK]": None,
    "mi[US]": None,
    "rod[US]": None,
    "yd[BnA]": None,
    "yd[BnB]": None,
    "yd[Cla]": None,
    "yd[Ind]": None,
    "yd[Ind37]": None,
    "yd[Ind62]": None,
    "yd[Ind75]": None,
    "yd[Se]": None,
    "yd[SeT]": None,
    "yd[US]": None,
    "m3/m2": None,
    "0.1 ft": None,
    "0.1 ft[US]": None,
    "0.1 in": None,
    "0.1 yd": None,
    "deltaF/s": None,
    "deltaK/s": None,
    "deltaC/kPa": None,
    "deltaF/psi": None,
    "deltaK/Pa": None,
    "deltaK/W": None,
    "deltaC.m2.h/kcal[th]": None,
    "deltaF.ft2.h/Btu[IT]": None,
    "deltaK.m2/kW": None,
    "deltaK.m2/W": None,
    "A/cm2": None,
    "A/ft2": None,
    "A/mm2": None,
    "mA/cm2": None,
    "mA/ft2": None,
    "uA/cm2": None,
    "uA/in2": None,
    "A/m2": None,
    "$": None,
    "$/t": None,
    "$/ton[US]": None,
    "A.m2": None,
    "C/cm2": None,
    "C/mm2": None,
    "mC/m2": None,
    "C/m2": None,
    "A.s/m3": None,
    "C/cm3": None,
    "C/mm3": None,
    "C/m3": None,
    "cd/m2": None,
    "chain[BnA]": None,
    "chain[BnB]": None,
    "chain[Cla]": None,
    "chain[Ind37]": None,
    "chain[Se]": None,
    "chain[SeT]": None,
    "chain[US]": None,
    "1/wk": None,
    "ccgr": None,
    "mila": None,
    "mina": None,
    "rev": None,
    "seca": None,
    "0.001 seca": None,
    "0.01 dega/ft": None,
    "1/30 dega/ft": None,
    "1/30 dega/m": None,
    "dega/ft": None,
    "dega/m": None,
    "rev/ft": None,
    "rev/m": None,
    "rad/m3": None,
    "rad/ft3": None,
    "dega/h": None,
    "dega/min": None,
    "dega/s": None,
    "rev/s": None,
    "rad/s2": None,
    "deltaC": None,
    "deltaF": None,
    "deltaR": None,
    "deltaK": None,
    "0.01 deltaF/ft": None,
    "deltaC/ft": None,
    "deltaC/hm": None,
    "deltaC/km": None,
    "deltaC/m": None,
    "deltaF/ft": None,
    "deltaF/m": None,
    "deltaK/km": None,
    "deltaK/m": None,
    "deltaC/h": None,
    "deltaC/min": None,
    "deltaC/s": None,
    "deltaF/h": None,
    "deltaF/min": None,
    "000 m3/m3": None,
    "Btu[IT]/(hp.h)": None,
    "0.01 ct/t": None,
    "oz t/ton[US]": None,
    "m/(m.deltaK)": None,
    "m3/(m3.deltaK)": None,
    "in/(in.deltaF)": None,
    "mm/(mm.deltaK)": None,
    "1E-6 m3/(m3.deltaC)": None,
    "1E-6 m3/(m3.deltaF)": None,
    "ppm[vol]/deltaC": None,
    "ppm[vol]/deltaF": None,
    "1E-9 1/ft": None,
    "mi[US]2": None,
    #
    # All the values below this point are complete,
    # and all the values above are incomplete.
    #
    "ft3/(d.ft)": "ft^3/(d.ft)",
    "ft/lbm": "ft/lb",
    "cm2/s": "cm^2/s",
    "ft2/h": "ft^2/h",
    "ft2/s": "ft^2/s",
    "in2/s": "in^2/s",
    "m2/d": "m^2/d",
    "m2/h": "m^2/h",
    "mm2/s": "mm^2/s",
    "m/s2": "m/s^2",
    "cm/s2": "cm/s^2",
    "ft/s2": "ft/s^2",
    "in/s2": "in/s^2",
    "dm3/m": "dm^3/m",
    "ft3/ft": "ft^3/ft",
    "gal[UK]/mi": "UK_gallon/mi",
    "gal[US]/ft": "gallon/ft",
    "gal[US]/mi": "gallon/mi",
    "in3/ft": "in^3/ft",
    "m3/km": "m^3/km",
    "m2": "m^2",
    "ft2": "ft^2",
    "mi2": "mi^2",
    "yd2": "yd^2",
    "m2/kg": "m^2/kg",
    "cm2/g": "cm^2/g",
    "ft2/lbm": "ft^2/lb",
    "m2/g": "m^2/g",
    "m2/mol": "m^2/mol",
    "m2/s": "m^2/s",
    "m3/(s.m)": "m^3/(s.m)",
    "mol.m2/(mol.s)": "mol.m^2/(mol.s)",
    "Pa.s.m3/kg": "Ps.s.m^3/kg",
    "footcandle": "lm/ft^2",
    "lm/m2": "lm/m^2",
    "footcandle.s": "(lm/ft^2).s",
    "gal[UK]/ft3": "UK_gallon/ft^3",
    "gal[US]/bbl": "gallon/bbl",
    "gal[US]/ft3": "gallon/ft^3",
    "L/m3": "L/m^3",
    "m3/(ha.m)": "m^3/(ha.m)",
    "m3/bbl": "m^3/bbl",
    "mL/gal[UK]": "mL/UK_gallon",
    "mL/gal[US]": "mL/gallon",
    "b/cm3": "b/cm^3",
    "ft2/in3": "ft^2/in^3",
    "m2/cm3": "m^2/cm^3",
    "m2/m3": "m^2/m^3",
    "1/ft2": "1/ft^2",
    "1/km2": "1/km^2",
    "1/mi2": "1/mi^2",
    "1/m2": "1/m^2",
    "m/m3": "m/m^3",
    "ft/ft3": "ft/ft^3",
    "ft/gal[US]": "ft/gallon",
    "1/gal[UK]": "1/UK_gallon",
    "1/gal[US]": "1/gallon",
    "km/dm3": "km/dm^3",
    "1/ft3": "1/ft^3",
    "1/m3": "1/m^3",
    "1/lbm": "1/lb",
    "mi/gal[UK]": "mi/UK_gallon",
    "mi/gal[US]": "mi/gallon",
    "m3/m": "m^3/m",
    "cm2": "cm^2",
    "km2": "km^2",
    "mm2": "mm^2",
    "um2": "um^2",
    "dega": "degree",
    "inH2O[60degF]": "inch_H2O_60F",
    "inHg[32degF]": "inch_Hg_32F",
    "inHg[60degF]": "inch_Hg_60F",
    "ton[US]/ft2": "short_ton/ft^2",
    "lbm.ft2/s2": "lb.ft^2/s^2",
    "hp[elec]": "electrical_horsepower",
    "hp[hyd]": "hydraulic_horsepower",
    "hp[metric]": "metric_horsepower",
    "ccal[th]": "ccal_th",
    "dcal[th]": "dcal_th",
    "Ecal[th]": "Ecal_th",
    "fcal[th]": "fcal_th",
    "Gcal[th]": "Gcal_th",
    "kcal[th]": "kcal_th",
    "mcal[th]": "mcal_th",
    "Mcal[th]": "Mcal_th",
    "ncal[th]": "ncal_th",
    "pcal[th]": "pcal_th",
    "Tcal[th]": "Tcal_th",
    "ucal[th]": "ucal_th",
    "Btu[IT]/h": "Btu_it/h",
    "Btu[IT]/min": "Btu_it/min",
    "Btu[IT]/s": "Btu_it/s",
    "cal[th]/h": "cal/h",
    "kcal[th]/h": "kcal/h",
    "ucal[th]/s": "ucal/h",
    "floz[UK]": "UK_fluid_ounce",
    "floz[US]": "fluid_ounce",
    "gal[UK]": "UK_gallon",
    "gal[US]": "gallon",
    "pt[UK]": "UK_pint",
    "pt[US]": "pint",
    "qt[UK]": "UK_quart",
    "qt[US]": "quart",
    "cm3": "cm^3",
    "dm3": "dm^3",
    "km3": "km^3",
    "mm3": "mm^3",
    "um2.m": "um^2.m",
    "m3": "m^3",
    "ft3": "ft^3",
    "in3": "in^3",
    "mi3": "mi^3",
    "yd3": "yd^3",
    "m3/rad": "m^3/rad",
    "ft3/rad": "ft^3/rad",
    "m3/kg": "m^3/kg",
    "bbl/ton[UK]": "bbl/long_ton",
    "bbl/ton[US]": "bbl/short_ton",
    "cm3/g": "cm^3/g",
    "dm3/kg": "dm^3",
    "dm3/t": "dm^3/t",
    "ft3/kg": "ft^3/kg",
    "ft3/lbm": "ft^2/lb",
    "gal[UK]/lbm": "UK_gallon/lb",
    "gal[US]/lbm": "gallon/lb",
    "gal[US]/ton[UK]": "gallon/long_ton",
    "gal[US]/ton[US]": "gallon/short_ton",
    "L/ton[UK]": "L/long_ton",
    "m3/g": "m^3/g",
    "m3/t": "m^3/t",
    "m3/ton[UK]": "m^3/long_ton",
    "m3/ton[US]": "m^3/short_ton",
    "m3/mol": "m^3/mol",
    "dm3/kmol": "dm^3/kmol",
    "m3/kmol": "m^3/kmol",
    "m3/s": "m^3/s",
    "cm3/h": "cm^3/h",
    "cm3/min": "cm^3/min",
    "cm3/s": "cm^3/s",
    "dm3/s": "dm^3/s",
    "ft3/d": "ft^3/d",
    "ft3/h": "ft^3/h",
    "ft3/min": "ft^3/min",
    "ft3/s": "ft^3/s",
    "gal[UK]/d": "UK_gallon/d",
    "gal[UK]/h": "UK_gallon/h",
    "gal[UK]/min": "UK_gallon/min",
    "gal[US]/d": "gallon/d",
    "gal[US]/h": "gallon/h",
    "gal[US]/min": "gallon/min",
    "m3/d": "m^3/d",
    "m3/h": "m^3/h",
    "m3/min": "m^3/min",
    "m3/s2": "m^3/s^2",
    "bbl/d2": "bbl/d^2",
    "bbl/h2": "bbl/h^2",
    "dm3/s2": "dm^3/s^2",
    "ft3/d2": "ft^3/d^2",
    "ft3/h2": "ft^3/h^2",
    "ft3/min2": "ft^3/min^2",
    "ft3/s2": "ft^3/s^2",
    "gal[UK]/h2": "UK_gallon/h^2",
    "gal[UK]/min2": "UK_gallon/min^2",
    "gal[US]/h2": "gallon/H^2",
    "gal[US]/min2": "gallon/min^2",
    "L/s2": "L/s^2",
    "m3/d2": "m^3/d^2",
    "nohm.mil2/ft": "nohm.mil^2/ft",
    "nohm.mm2/m": "nohm.mm^2/m",
    "ohm.m2/m": "ohm.m^2/m",
    "N.m2": "N.m^2",
    "dyne.cm2": "dyne.cm^2",
    "kgf.m2": "kg.m^2",
    "kN.m2": "kN,m^2",
    "lbf.in2": "lb.in^2",
    "mN.m2": "mN.m^2",
    "pdl.cm2": "pdl.cm^2",
    "tonf[UK].ft2": "long_ton.ft^2",
    "tonf[US].ft2": "short_ton.ft^2",
    "m2/(Pa.s)": "m^2/(Pa.s)",
    "ft3/(ft.psi.d)": "ft^3/(ft.psi.d)",
    "m2/(kPa.d)": "m^2/(kPa.d)",
    "mD.ft2/(lbf.s)": "mD.ft^2/(lb.s)",
    "mD.in2/(lbf.s)": "mD.in^2/(lb.s)",
    "cm4": "cm^4",
    "m4": "m^4",
    "in4": "in^4",
    "m4/s": "m^4/s",
    "m3/(Pa.s)": "m^3/(Pa.s)",
    "m3/(bar.d)": "m^3/(bar.d)",
    "m3/(bar.h)": "m^3/(bar.h)",
    "m3/(bar.min)": "m^3/(bar.min)",
    "m3/(kPa.d)": "m^3/(kPa.d)",
    "m3/(kPa.h)": "m^3/(kPa.h)",
    "m3/(psi.d)": "m^3/(psi.d)",
    "m3/Pa": "m^3/Pa",
    "m3/kPa": "m^3/kPa",
    "lbm.ft": "lb.ft",
    "lbm.ft/s": "lb.ft/s",
    "J.m/m2": "J.m/m^2",
    "kcal[th].m/cm2": "kcal_th.m/cm^2",
    "ton[US]": "short_ton",
    "ton[UK]": "long_ton",
    "kton[US]": "kshort_ton",
    "kton[UK]": "kshort_ton",
    "tonf[US]": "short_ton",
    "tonf[UK]": "long_ton",
    "Mton[US]": "Mshort_ton",
    "Mton[UK]": "Mlong_ton",
    "tonf[US].mi/ft": "short_ton.mi/ft",
    "m3/J": "m^3/J",
    "dm3/(kW.h)": "dm^3/(kW.h)",
    "dm3/MJ": "dm^3/MJ",
    "m3/(kW.h)": "m^3/(kW.h)",
    "mm3/J": "mm^3/J",
    "ozm[troy]": "troy_ounce",
    "cwt[US]": "cwt",
    "cwt[UK]": "UK_cwt",
    "pt[UK]/(hp.h)": "UK_pint/(hp.h)",
    "ozm": "oz",
    "lbm": "lb",
    "klbm": "klb",
    "Mlbm": "Mlb",
    "kg.m/cm2": "kg.m/cm^2",
    "klbm/in": "klb/in",
    "lbm/ft": "lb/ft",
    "kg/m2": "kg/m^2",
    "lbm/ft2": "lb/ft^2",
    "Mg/m2": "Mg/m^2",
    "kg/(m2.s)": "kg/(m^2.s)",
    "g.ft/(cm3.s)": "g.ft/(cm^3.s)",
    "g.m/(cm3.s)": "g.m/(cm^3.s)",
    "lbm/(ft2.s)": "lb(ft^2.s)",
    "lbm/(ft2.h)": "lb(ft^2.h)",
    "cm3/m3": "cm^3/m^3",
    "dm3/m3": "dm^3/m^3",
    "ft3/bbl": "ft^3/bbl",
    "bbl/ft3": "bbl/ft^3",
    "bbl/m3": "bbl/m^3",
    "cm3/L": "cm^3/L",
    "N/m3": "N/m^3",
    "lbf/gal[US]": "lbf/gallon",
    "lbf/ft3": "lbf/ft^3",
    "g/cm3": "g/cm^3",
    "g/dm3": "g/db^3",
    "g/gal[UK]": "g/UK_gallon",
    "g/gal[US]": "g/gallon",
    "grain/ft3": "grain/ft^3",
    "grain/gal[US]": "grain/gallon",
    "lbm/bbl": "lb/bbl",
    "lbm/ft3": "lb/ft^3",
    "lbm/gal[UK]": "lb/UK_gallon",
    "lbm/gal[US]": "lb/gallon",
    "lbm/in3": "lb/in^3",
    "kg/dm3": "kg/dm^3",
    "mg/dm3": "mg/dm^3",
    "mg/gal[US]": "mg/gallon",
    "Mg/m3": "Mg/m^3",
    "kg/m3": "kg/m^3",
    "g/m3": "g/m^3",
    "mg/m3": "mg/m^3",
    "t/m3": "t/m^3",
    "ug/cm3": "ug/cm^3",
    "kg/m4": "kg/m^4",
    "g/cm4": "g/cm^4",
    "kg/dm4": "kg/dm^4",
    "lbm/(gal[UK].ft)": "lb/(UK_gallon.ft)",
    "lbm/(gal[US].ft)": "lb/(gallon.ft)",
    "lbm/ft4": "lb/ft^4",
    "Pa.s2/m3": "Pa.^2s/m^3",
    "Pa.s/m3": "Pa.s/m^3",
    "Pa/m3": "Pa/m^3",
    "psi2.d/(cP.ft3)": "psi^2.d/(cP.ft^3)",
    "lbm/(ft.h)": "lb/(ft.h)",
    "lbm/(ft.s)": "lb/(ft.s)",
    "dyne.s/cm2": "dyne.s/cm^2",
    "kgf.s/m2": "kgf.s/m^2",
    "lbf.s/ft2": "lbf.s/ft^2",
    "lbf.s/in2": "lbf.s/in^2",
    "N.s/m2": "N.s/m^2",
    "J/m3": "J/m^3",
    "Btu[IT]/bbl": "Btu_it/bbl",
    "Btu[IT]/ft3": "Btu_it/ft^3",
    "Btu[IT]/gal[UK]": "Btu_it/UK_gallon",
    "Btu[IT]/gal[US]": "Btu_it/gallon",
    "cal[th]/cm3": "cal_th/cm^3",
    "cal[th]/mL": "cal_th/mL^3",
    "cal[th]/mm3": "cal_th/mm^3",
    "erg/m3": "erg/m^3",
    "erg/cm3": "erg/cm^3",
    "J/dm3": "J/dm^3",
    "kcal[th]/m3": "kcal_th/m^3",
    "kcal[th]/cm3": "kcal_th/cm^3",
    "kJ/dm3": "kJ/dm^3",
    "kJ/m3": "kJ/m^3",
    "kW.h/dm3": "kW.h/dm^3",
    "kW.h/m3": "kW.h/m^3",
    "lbf.ft/gal[US]": "lbf.ft/gallon",
    "MJ/m3": "MJ/m^3",
    "MW.h/m3": "MW.h/m^3",
    "dyne/cm2": "dyne/cm^2",
    "kgf/m2": "kgf/m^2",
    "kgf/cm2": "kgf/cm^2",
    "kgf/mm2": "kgf/mm^2",
    "kN/m2": "kN/m^2",
    "lbf/ft2": "lbf/ft^2",
    "N/m2": "N/m^2",
    "N/mm2": "N/mm^2",
    "Pa2/(Pa.s)": "Pa^2/(Pa.s)",
    "W/m3": "W/m^3",
    "bar2/cP": "bar^2/cP",
    "kPa2/cP": "kPa^2/cP",
    "psi2/cP": "psi^2/cP",
    "Btu[IT]/(h.ft3)": "Btu_it/(h.ft^3)",
    "Btu[IT]/(s.ft3)": "Btu_it/(s.ft^3)",
    "cal[th]/(h.cm3)": "cal_th/(h.cm^3)",
    "cal[th]/(s.cm3)": "cal_th/(s.cm^3)",
    "hp/ft3": "hp/ft^3",
    "kW/m3": "kW/m^3",
    "uW/m3": "uW/m^3",
    "W/(m2.sr)": "W/(m^2.sr)",
    "lbm/s": "lb/s",
    "lbm/min": "lb/min",
    "lbm/h": "lb/h",
    "lbm/d": "lb/d",
    "J/m2": "J/m^2",
    "erg/cm2": "erg/cm^2",
    "J/cm2": "J/cm^2",
    "kgf.m/cm2": "kgf.m/cm^2",
    "lbf.ft/in2": "lbf.ft/in^2",
    "mJ/cm2": "mJ/cm^2",
    "mJ/m2": "mJ/m^2",
    "Btu[IT]/(h.ft2)": "Btu_it/(h.ft^2)",
    "Btu[IT]/(s.ft2)": "Btu_it/(s.ft^2)",
    "cal[th]/(h.cm2)": "cal_th/(h.cm^2)",
    "hp/in2": "hp/in^2",
    "hp[hyd]/in2": "hp/in^2",
    "kW/cm2": "kW/cm^2",
    "kW/m2": "kW/m^2",
    "mW/m2": "m/m^2",
    "ucal[th]/(s.cm2)": "ucal_th/(s.cm^2)",
    "W/m2": "W/m^2",
    "W/cm2": "W/cm^2",
    "W/mm2": "W/mm^2",
    "GPa2": "GPa^2",
    "kPa2": "kPa^2",
    "kpsi2": "kpsi^2",
    "in2/ft2": "in^2/ft^2",
    "in2": "in^2",
    "Pa2": "Pa^2",
    "bar2": "bar^2",
    "psi2": "psi^2",
    "mol/m2": "mol/m^2",
    "mol/(s.m2)": "mol/(s.m^2)",
    "mol/m3": "mol/m^3",
    "kmol/m3": "kmol/m^3",
    "s/m3": "s/m^3",
    "d/ft3": "d/ft^3",
    "d/m3": "d/m^3",
    "h/ft3": "h/ft^3",
    "h/m3": "h/m^3",
    "s/ft3": "s/ft^3",
    "s/qt[UK]": "s/UK_quart",
    "s/qt[US]": "s/quart",
    "lbm/(hp.h)": "lb/(hp.h)",
}

# build the look up table mapping Pint units
# to the corresponding Unit_V1_0_1 enumeration value
_pint_lookup: dict[str, Unit] = dict()
for e in typing.get_args(Unit):
    for p in e:
        try:
            name = p.value
            if name in _translation_table:
                name = _translation_table[name]
                if name is None:
                    continue
            pt = PintType(name)
            pn = str(pt.units)
            _pint_lookup[pn] = p
        except (UndefinedUnitError, ValueError, AssertionError) as e:
            logger.warning(f"Unable to map {p.value} to pint type {e}")
