name: Build and publish evo-data-converters-gef

permissions:
  # Required for publishing release artifacts
  contents: write
  # Required for PyPI trusted publishing
  id-token: write

on:
  release:
    types: [released]

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  run-tests:
    if: startsWith(github.event.release.tag_name, 'evo-data-converters-gef@')
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
        package:
          - common
          - gef
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/testing
        with:
          PACKAGE: ${{ matrix.package }}
          PYTHON_VERSION: ${{ matrix.python-version }}

  build-and-publish:
    name: Build and publish package
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/install-uv

      - name: Build package
        shell: bash
        run: uv build --package evo-data-converters-gef

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Upload artifact to GitHub Release
        shell: bash
        run: gh release upload ${{ github.event.release.tag_name }} dist/*
